import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('supply_chain_data.csv')

#Q1
#What is the total revenue generated by each product type?
#Chart Type: Bar Chart This chart aggregates the revenue across the main product categories (Haircare, Skincare, Cosmetics) to identify the highest-earning segment.
# 1. Bar Chart: Total Revenue by Product Type
sns.set_theme(style="whitegrid")
plt.figure(figsize=(10, 6))
rev_by_product = df.groupby('Product type')['Revenue generated'].sum().sort_values(ascending=False).reset_index()
sns.barplot(data=rev_by_product, x='Product type', y='Revenue generated', palette='viridis')
plt.title('Total Revenue Generated by Product Type')
plt.ylabel('Total Revenue')
plt.xlabel('Product Type')
plt.savefig('q1_revenue_by_product.png')
plt.close()
print(rev_by_product)

#Q2
#How are sales distributed across different customer demographics?
#Chart Type: Pie Chart A pie chart representing the market share of different demographic groups (Male, Female, Non-binary, Unknown) in the supply chain.
# 2. Pie Chart: Customer Demographics Distribution
plt.figure(figsize=(8, 8))
demo_counts = df['Customer demographics'].value_counts()
plt.pie(demo_counts, labels=demo_counts.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette('pastel'))
plt.title('Distribution of Customer Demographics')
plt.savefig('q2_customer_demographics.png')
plt.close()
print(demo_counts)

#Q3
#Is there a relationship between product price and the number of products sold?
#Chart Type: Scatter Plot This plot explores whether higher-priced items sell fewer units, with data points colored by product type and sized by revenue.
# 3. Scatter Plot: Price vs Number of products sold
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='Price', y='Number of products sold', hue='Product type', size='Revenue generated', sizes=(20, 200))
plt.title('Price vs Number of Products Sold')
plt.savefig('q3_price_vs_sold.png')
plt.close()

#Q4
#What is the frequency distribution of manufacturing costs?
#Chart Type: Histogram with KDE A histogram showing the spread of manufacturing costs across the entire inventory, identifying common price points for production.
# 4. Histogram: Distribution of Manufacturing Costs
plt.figure(figsize=(10, 6))
sns.histplot(df['Manufacturing costs'], bins=15, kde=True, color='skyblue')
plt.title('Distribution of Manufacturing Costs')
plt.savefig('q4_mfg_costs_dist.png')
plt.close()

#Q5
#How do defect rates vary across different transportation modes?
#Chart Type: Box Plot A box plot comparing the distribution of defect rates for Road, Rail, Air, and Sea transport to identify which mode is most prone to issues.
# 5. Box Plot: Defect rates by Transportation mode
plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x='Transportation modes', y='Defect rates', palette='Set2')
plt.title('Defect Rates across Transportation Modes')
plt.savefig('q5_defects_by_transport.png')
plt.close()

#Q6
#What is the density and range of shipping costs for each carrier?
#Chart Type: Violin Plot Combining box plots and density plots, this visualization shows the probability density of shipping costs for Carriers A, B, and C.
# 6. Violin Plot: Shipping costs for each Shipping carrier
plt.figure(figsize=(10, 6))
sns.violinplot(data=df, x='Shipping carriers', y='Shipping costs', inner="quartile", palette='muted')
plt.title('Distribution of Shipping Costs by Carrier')
plt.savefig('q6_shipping_costs_violin.png')
plt.close()

#Q7
#What are the correlations between different numerical metrics in the supply chain?
#Chart Type: Heatmap A correlation matrix heatmap that identifies relationships between price, revenue, lead times, stock levels, and costs.
# 7. Heatmap: Correlation between numerical variables
plt.figure(figsize=(12, 10))
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
corr = df[numeric_cols].corr()
sns.heatmap(corr, annot=True, fmt=".2f", cmap='coolwarm', square=True)
plt.title('Correlation Heatmap of Numerical Features')
plt.tight_layout()
plt.savefig('q7_correlation_heatmap.png')
plt.close()

#Q8
#What are the quality inspection results for each product category?
#Chart Type: Stacked Bar Chart This chart breaks down the "Pass," "Fail," and "Pending" inspection results for each product type to assess quality control performance.
# 8. Stacked Bar Chart: Inspection results by Product Type
plt.figure(figsize=(10, 6))
inspection_pivot = df.groupby(['Product type', 'Inspection results']).size().unstack().fillna(0)
inspection_pivot.plot(kind='bar', stacked=True, figsize=(10, 6), color=['#ff9999','#66b3ff','#99ff99'])
plt.title('Inspection Results by Product Type')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.legend(title='Inspection Result')
plt.savefig('q8_inspection_results.png')
plt.close()

#Q9
#How do price and revenue compare when factoring in current stock levels?
#Chart Type: Bubble Chart A scatter plot where the size of the bubbles represents the stock level, showing how inventory volume relates to pricing and revenue generation.
# 9. Bubble Chart: Price vs Revenue (Bubble Size = Stock levels)
plt.figure(figsize=(10, 6))
plt.scatter(df['Price'], df['Revenue generated'], s=df['Stock levels']*5, alpha=0.5, c=df['Price'], cmap='viridis')
plt.title('Bubble Chart: Price vs Revenue (Size = Stock levels)')
plt.xlabel('Price')
plt.ylabel('Revenue Generated')
plt.colorbar(label='Price Scale')
plt.savefig('q9_bubble_chart.png')
plt.close()

#Q10
#Which supplier has the highest average manufacturing lead time?
#Chart Type: Horizontal Bar Chart A sorted horizontal bar chart identifying which suppliers take the longest on average to complete manufacturing processes.
# 10. Horizontal Bar Chart: Avg Manufacturing Lead Time by Supplier
plt.figure(figsize=(10, 6))
avg_lead_time = df.groupby('Supplier name')['Manufacturing lead time'].mean().sort_values().reset_index()
sns.barplot(data=avg_lead_time, y='Supplier name', x='Manufacturing lead time', palette='magma')
plt.title('Average Manufacturing Lead Time by Supplier')
plt.xlabel('Average Lead Time (Days)')
plt.ylabel('Supplier Name')
plt.savefig('q10_avg_lead_time_supplier.png')
plt.close()
print(avg_lead_time)